apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.services.backendname }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployments.backendname }}
  ports:
  - port: {{ .Values.image.backend.port }}
    targetPort: {{ .Values.image.backend.port }}
    
